console.log("Hello Winc Academy");
let name = "Rishaan";
console.log(name);
console.log("4 + 4");
let math = 10 + 7;
let math2 = 9 + 3 * 6;
let mathCombine = math2 + 3;
let mathSuperCombine = (math2 * math) / 2;
console.log('dit moet 17 zijn',math);
console.log(math2);
console.log(mathCombine);
console.log(math2 * math);
console.log(459 / 2);
console.log(6 + 4);
console.log(mathSuperCombine);
console.log(10 % 4);
console.log(5 ** 3);
let age = 33;
console.log(typeof age);
